working with sql

In [2]:
!pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
      --------------------------------------- 0.3/11.9 MB ? eta -:--:--
      --------------------------------------- 0.3/11.9 MB ? eta -:--:--
      --------------------------------------- 0.3/11.9 MB ? eta -:--:--
     - ------------------------------------- 0.5/11.9 MB 367.0 kB/s eta 0:00:31
     - ------------------------------------- 0.5/11.9 MB 367.0 kB/s eta 0:00:31
     - ------------------------------------- 0.5/11.9 MB 367.0 kB/s eta 0:00:31
     -- ------------------------------------ 0.8/11.9 MB 405.5 kB/s eta 0:00:28
     -- ------------------------------------ 0.8/11.9 MB 405.5 kB/s eta 0:00:28
     --- ----------------------------------- 1.0/11.9 MB 438.3 kB/s eta 0:00:25
     --- ----------------------------------- 1.0/11.9 MB 438.3 kB/s eta 0:00:25
     --- ----------------------------------- 1.0/11.9 MB 438.3 kB/s eta 0:00:25
     ---- ---------------------------------- 1.3/11.9 MB 441.6 kB/s eta 0:00:24
     ----- --------------------------------- 1.6/11.9 MB 494.8 kB/s eta 0:00:21
     ------ -------------------------------- 1.8/11.9 MB 551.1 kB/s eta 0:00:19
     ------ -------------------------------- 2.1/11.9 MB 590.3 kB/s eta 0:00:17
     ------ -------------------------------- 2.1/11.9 MB 590.3 kB/s eta 0:00:17
     ------ -------------------------------- 2.1/11.9 MB 590.3 kB/s eta 0:00:17
     ------- ------------------------------- 2.4/11.9 MB 581.4 kB/s eta 0:00:17
     ------- ------------------------------- 2.4/11.9 MB 581.4 kB/s eta 0:00:17
     -------- ------------------------------ 2.6/11.9 MB 576.5 kB/s eta 0:00:17
     -------- ------------------------------ 2.6/11.9 MB 576.5 kB/s eta 0:00:17
     -------- ------------------------------ 2.6/11.9 MB 576.5 kB/s eta 0:00:17
     -------- ------------------------------ 2.6/11.9 MB 576.5 kB/s eta 0:00:17
     -------- ------------------------------ 2.6/11.9 MB 576.5 kB/s eta 0:00:17
     -------- ------------------------------ 2.6/11.9 MB 576.5 kB/s eta 0:00:17
     -------- ------------------------------ 2.6/11.9 MB 576.5 kB/s eta 0:00:17
     -------- ------------------------------ 2.6/11.9 MB 576.5 kB/s eta 0:00:17
     --------- ----------------------------- 2.9/11.9 MB 460.5 kB/s eta 0:00:20
     --------- ----------------------------- 2.9/11.9 MB 460.5 kB/s eta 0:00:20
     --------- ----------------------------- 2.9/11.9 MB 460.5 kB/s eta 0:00:20
     --------- ----------------------------- 2.9/11.9 MB 460.5 kB/s eta 0:00:20
     --------- ----------------------------- 2.9/11.9 MB 460.5 kB/s eta 0:00:20
     --------- ----------------------------- 2.9/11.9 MB 460.5 kB/s eta 0:00:20
     --------- ----------------------------- 2.9/11.9 MB 460.5 kB/s eta 0:00:20
     ---------- ---------------------------- 3.1/11.9 MB 402.9 kB/s eta 0:00:22
     ---------- ---------------------------- 3.1/11.9 MB 402.9 kB/s eta 0:00:22
     ---------- ---------------------------- 3.1/11.9 MB 402.9 kB/s eta 0:00:22
     ---------- ---------------------------- 3.1/11.9 MB 402.9 kB/s eta 0:00:22
     ---------- ---------------------------- 3.1/11.9 MB 402.9 kB/s eta 0:00:22
     ---------- ---------------------------- 3.1/11.9 MB 402.9 kB/s eta 0:00:22
     ---------- ---------------------------- 3.1/11.9 MB 402.9 kB/s eta 0:00:22
     ---------- ---------------------------- 3.1/11.9 MB 402.9 kB/s eta 0:00:22
     ---------- ---------------------------- 3.1/11.9 MB 402.9 kB/s eta 0:00:22
     ---------- ---------------------------- 3.1/11.9 MB 402.9 kB/s eta 0:00:22
     ---------- ---------------------------- 3.1/11.9 MB 402.9 kB/s eta 0:00:22
     ---------- ---------------------------- 3.1/11.9 MB 402.9 kB/s eta 0:00:22
     ---------- ---------------------------- 3.1/11.9 MB 402.9 kB/s eta 0:00:22
     ---------- ---------------------------- 3.1/11.9 MB 402.9 kB/s eta 0:00:22
     ---------- ---------------------------- 3.1/11.9 MB 402.9 kB/s eta 0:00:22
     ----------- --------------------------- 3.4/11.9 MB 299.1 kB/s eta 0:00:29
     ----------- --------------------------- 3.4/11.9 MB 299.1 kB/s eta 0:00:29
     ----------- --------------------------- 3.4/11.9 MB 299.1 kB/s eta 0:00:29
     ----------- --------------------------- 3.4/11.9 MB 299.1 kB/s eta 0:00:29
     ------------ -------------------------- 3.7/11.9 MB 299.9 kB/s eta 0:00:28
     ------------ -------------------------- 3.7/11.9 MB 299.9 kB/s eta 0:00:28
     ------------ -------------------------- 3.7/11.9 MB 299.9 kB/s eta 0:00:28
     ------------ -------------------------- 3.7/11.9 MB 299.9 kB/s eta 0:00:28
     ------------ -------------------------- 3.7/11.9 MB 299.9 kB/s eta 0:00:28
     ------------ -------------------------- 3.7/11.9 MB 299.9 kB/s eta 0:00:28
     ------------ -------------------------- 3.7/11.9 MB 299.9 kB/s eta 0:00:28
     ------------ -------------------------- 3.7/11.9 MB 299.9 kB/s eta 0:00:28
     ------------ -------------------------- 3.7/11.9 MB 299.9 kB/s eta 0:00:28
     ------------ -------------------------- 3.7/11.9 MB 299.9 kB/s eta 0:00:28
     ------------ -------------------------- 3.7/11.9 MB 299.9 kB/s eta 0:00:28
     ------------ -------------------------- 3.7/11.9 MB 299.9 kB/s eta 0:00:28
     ------------ -------------------------- 3.7/11.9 MB 299.9 kB/s eta 0:00:28
     ------------ -------------------------- 3.7/11.9 MB 299.9 kB/s eta 0:00:28
     ------------ -------------------------- 3.9/11.9 MB 257.9 kB/s eta 0:00:31
     ------------- ------------------------- 4.2/11.9 MB 271.3 kB/s eta 0:00:29
     ------------- ------------------------- 4.2/11.9 MB 271.3 kB/s eta 0:00:29
     ------------- ------------------------- 4.2/11.9 MB 271.3 kB/s eta 0:00:29
     ------------- ------------------------- 4.2/11.9 MB 271.3 kB/s eta 0:00:29
     -------------- ------------------------ 4.5/11.9 MB 275.4 kB/s eta 0:00:27
     -------------- ------------------------ 4.5/11.9 MB 275.4 kB/s eta 0:00:27
     -------------- ------------------------ 4.5/11.9 MB 275.4 kB/s eta 0:00:27
     -------------- ------------------------ 4.5/11.9 MB 275.4 kB/s eta 0:00:27
     -------------- ------------------------ 4.5/11.9 MB 275.4 kB/s eta 0:00:27
     -------------- ------------------------ 4.5/11.9 MB 275.4 kB/s eta 0:00:27
     -------------- ------------------------ 4.5/11.9 MB 275.4 kB/s eta 0:00:27
     -------------- ------------------------ 4.5/11.9 MB 275.4 kB/s eta 0:00:27
     -------------- ------------------------ 4.5/11.9 MB 275.4 kB/s eta 0:00:27
     -------------- ------------------------ 4.5/11.9 MB 275.4 kB/s eta 0:00:27
     -------------- ------------------------ 4.5/11.9 MB 275.4 kB/s eta 0:00:27
     -------------- ------------------------ 4.5/11.9 MB 275.4 kB/s eta 0:00:27
     -------------- ------------------------ 4.5/11.9 MB 275.4 kB/s eta 0:00:27
     -------------- ------------------------ 4.5/11.9 MB 275.4 kB/s eta 0:00:27
     -------------- ------------------------ 4.5/11.9 MB 275.4 kB/s eta 0:00:27
     -------------- ------------------------ 4.5/11.9 MB 275.4 kB/s eta 0:00:27
     --------------- ----------------------- 4.7/11.9 MB 239.7 kB/s eta 0:00:30
     --------------- ----------------------- 4.7/11.9 MB 239.7 kB/s eta 0:00:30
     --------------- ----------------------- 4.7/11.9 MB 239.7 kB/s eta 0:00:30
     --------------- ----------------------- 4.7/11.9 MB 239.7 kB/s eta 0:00:30
     --------------- ----------------------- 4.7/11.9 MB 239.7 kB/s eta 0:00:30
     --------------- ----------------------- 4.7/11.9 MB 239.7 kB/s eta 0:00:30
     --------------- ----------------------- 4.7/11.9 MB 239.7 kB/s eta 0:00:30
     --------------- ----------------------- 4.7/11.9 MB 239.7 kB/s eta 0:00:30
     --------------- ----------------------- 4.7/11.9 MB 239.7 kB/s eta 0:00:30
     --------------- ----------------------- 4.7/11.9 MB 239.7 kB/s eta 0:00:30
     --------------- ----------------------- 4.7/11.9 MB 239.7 kB/s eta 0:00:30
     --------------- ----------------------- 4.7/11.9 MB 239.7 kB/s eta 0:00:30
     --------------- ----------------------- 4.7/11.9 MB 239.7 kB/s eta 0:00:30
     --------------- ----------------------- 4.7/11.9 MB 239.7 kB/s eta 0:00:30
     ---------------- ---------------------- 5.0/11.9 MB 217.9 kB/s eta 0:00:32
     ---------------- ---------------------- 5.0/11.9 MB 217.9 kB/s eta 0:00:32
     ---------------- ---------------------- 5.0/11.9 MB 217.9 kB/s eta 0:00:32
     ---------------- ---------------------- 5.0/11.9 MB 217.9 kB/s eta 0:00:32
     ---------------- ---------------------- 5.0/11.9 MB 217.9 kB/s eta 0:00:32
     ---------------- ---------------------- 5.0/11.9 MB 217.9 kB/s eta 0:00:32
     ---------------- ---------------------- 5.0/11.9 MB 217.9 kB/s eta 0:00:32
     ---------------- ---------------------- 5.0/11.9 MB 217.9 kB/s eta 0:00:32
     ---------------- ---------------------- 5.0/11.9 MB 217.9 kB/s eta 0:00:32
     ---------------- ---------------------- 5.0/11.9 MB 217.9 kB/s eta 0:00:32
     ----------------- --------------------- 5.2/11.9 MB 209.3 kB/s eta 0:00:32
     ----------------- --------------------- 5.2/11.9 MB 209.3 kB/s eta 0:00:32
     ----------------- --------------------- 5.2/11.9 MB 209.3 kB/s eta 0:00:32
     ----------------- --------------------- 5.2/11.9 MB 209.3 kB/s eta 0:00:32
     ----------------- --------------------- 5.2/11.9 MB 209.3 kB/s eta 0:00:32
     ----------------- --------------------- 5.2/11.9 MB 209.3 kB/s eta 0:00:32
     ----------------- --------------------- 5.2/11.9 MB 209.3 kB/s eta 0:00:32
     ----------------- --------------------- 5.2/11.9 MB 209.3 kB/s eta 0:00:32
     ------------------ -------------------- 5.5/11.9 MB 207.0 kB/s eta 0:00:31
     ------------------ -------------------- 5.5/11.9 MB 207.0 kB/s eta 0:00:31
     ------------------ -------------------- 5.5/11.9 MB 207.0 kB/s eta 0:00:31
     ------------------ -------------------- 5.5/11.9 MB 207.0 kB/s eta 0:00:31
     ------------------ -------------------- 5.5/11.9 MB 207.0 kB/s eta 0:00:31
     ------------------ -------------------- 5.5/11.9 MB 207.0 kB/s eta 0:00:31
     ------------------ -------------------- 5.5/11.9 MB 207.0 kB/s eta 0:00:31
     ------------------ -------------------- 5.5/11.9 MB 207.0 kB/s eta 0:00:31
     ------------------ -------------------- 5.5/11.9 MB 207.0 kB/s eta 0:00:31
     ------------------ -------------------- 5.8/11.9 MB 201.6 kB/s eta 0:00:31
     ------------------ -------------------- 5.8/11.9 MB 201.6 kB/s eta 0:00:31
     ------------------ -------------------- 5.8/11.9 MB 201.6 kB/s eta 0:00:31
     ------------------ -------------------- 5.8/11.9 MB 201.6 kB/s eta 0:00:31
     ------------------ -------------------- 5.8/11.9 MB 201.6 kB/s eta 0:00:31
     ------------------ -------------------- 5.8/11.9 MB 201.6 kB/s eta 0:00:31
     ------------------ -------------------- 5.8/11.9 MB 201.6 kB/s eta 0:00:31
     ------------------ -------------------- 5.8/11.9 MB 201.6 kB/s eta 0:00:31
     ------------------ -------------------- 5.8/11.9 MB 201.6 kB/s eta 0:00:31
     ------------------ -------------------- 5.8/11.9 MB 201.6 kB/s eta 0:00:31
     ------------------ -------------------- 5.8/11.9 MB 201.6 kB/s eta 0:00:31
     ------------------ -------------------- 5.8/11.9 MB 201.6 kB/s eta 0:00:31
     ------------------ -------------------- 5.8/11.9 MB 201.6 kB/s eta 0:00:31
     ------------------ -------------------- 5.8/11.9 MB 201.6 kB/s eta 0:00:31
     ------------------ -------------------- 5.8/11.9 MB 201.6 kB/s eta 0:00:31
     ------------------ -------------------- 5.8/11.9 MB 201.6 kB/s eta 0:00:31
     ------------------ -------------------- 5.8/11.9 MB 201.6 kB/s eta 0:00:31
     ------------------ -------------------- 5.8/11.9 MB 201.6 kB/s eta 0:00:31
     ------------------ -------------------- 5.8/11.9 MB 201.6 kB/s eta 0:00:31
     ------------------ -------------------- 5.8/11.9 MB 201.6 kB/s eta 0:00:31
     ------------------ -------------------- 5.8/11.9 MB 201.6 kB/s eta 0:00:31
     ------------------ -------------------- 5.8/11.9 MB 201.6 kB/s eta 0:00:31
     ------------------- ------------------- 6.0/11.9 MB 159.3 kB/s eta 0:00:37
     ------------------- ------------------- 6.0/11.9 MB 159.3 kB/s eta 0:00:37
     ------------------- ------------------- 6.0/11.9 MB 159.3 kB/s eta 0:00:37
     ------------------- ------------------- 6.0/11.9 MB 159.3 kB/s eta 0:00:37
     ------------------- ------------------- 6.0/11.9 MB 159.3 kB/s eta 0:00:37
     ------------------- ------------------- 6.0/11.9 MB 159.3 kB/s eta 0:00:37
     ------------------- ------------------- 6.0/11.9 MB 159.3 kB/s eta 0:00:37
     ------------------- ------------------- 6.0/11.9 MB 159.3 kB/s eta 0:00:37
     ------------------- ------------------- 6.0/11.9 MB 159.3 kB/s eta 0:00:37
     -------------------- ------------------ 6.3/11.9 MB 123.5 kB/s eta 0:00:46
     -------------------- ------------------ 6.3/11.9 MB 123.5 kB/s eta 0:00:46
     -------------------- ------------------ 6.3/11.9 MB 123.5 kB/s eta 0:00:46
     -------------------- ------------------ 6.3/11.9 MB 123.5 kB/s eta 0:00:46
     -------------------- ------------------ 6.3/11.9 MB 123.5 kB/s eta 0:00:46
     -------------------- ------------------ 6.3/11.9 MB 123.5 kB/s eta 0:00:46
     -------------------- ------------------ 6.3/11.9 MB 123.5 kB/s eta 0:00:46
     -------------------- ------------------ 6.3/11.9 MB 123.5 kB/s eta 0:00:46
     -------------------- ------------------ 6.3/11.9 MB 123.5 kB/s eta 0:00:46
     -------------------- ------------------ 6.3/11.9 MB 123.5 kB/s eta 0:00:46
     -------------------- ------------------ 6.3/11.9 MB 123.5 kB/s eta 0:00:46
     -------------------- ------------------ 6.3/11.9 MB 123.5 kB/s eta 0:00:46
     -------------------- ------------------ 6.3/11.9 MB 123.5 kB/s eta 0:00:46
     -------------------- ------------------ 6.3/11.9 MB 123.5 kB/s eta 0:00:46
     -------------------- ------------------ 6.3/11.9 MB 123.5 kB/s eta 0:00:46
     -------------------- ------------------ 6.3/11.9 MB 123.5 kB/s eta 0:00:46
     --------------------- ----------------- 6.6/11.9 MB 117.6 kB/s eta 0:00:46
     --------------------- ----------------- 6.6/11.9 MB 117.6 kB/s eta 0:00:46
     --------------------- ----------------- 6.6/11.9 MB 117.6 kB/s eta 0:00:46
     --------------------- ----------------- 6.6/11.9 MB 117.6 kB/s eta 0:00:46
     --------------------- ----------------- 6.6/11.9 MB 117.6 kB/s eta 0:00:46
     --------------------- ----------------- 6.6/11.9 MB 117.6 kB/s eta 0:00:46
     --------------------- ----------------- 6.6/11.9 MB 117.6 kB/s eta 0:00:46
     --------------------- ----------------- 6.6/11.9 MB 117.6 kB/s eta 0:00:46
     --------------------- ----------------- 6.6/11.9 MB 117.6 kB/s eta 0:00:46
     --------------------- ----------------- 6.6/11.9 MB 117.6 kB/s eta 0:00:46
     --------------------- ----------------- 6.6/11.9 MB 117.6 kB/s eta 0:00:46
     --------------------- ----------------- 6.6/11.9 MB 117.6 kB/s eta 0:00:46
     --------------------- ----------------- 6.6/11.9 MB 117.6 kB/s eta 0:00:46
     --------------------- ----------------- 6.6/11.9 MB 117.6 kB/s eta 0:00:46
     --------------------- ----------------- 6.6/11.9 MB 117.6 kB/s eta 0:00:46
     --------------------- ----------------- 6.6/11.9 MB 117.6 kB/s eta 0:00:46
     --------------------- ----------------- 6.6/11.9 MB 117.6 kB/s eta 0:00:46
     ---------------------- ---------------- 6.8/11.9 MB 106.4 kB/s eta 0:00:48
     ---------------------- ---------------- 6.8/11.9 MB 106.4 kB/s eta 0:00:48
     ---------------------- ---------------- 6.8/11.9 MB 106.4 kB/s eta 0:00:48
     ---------------------- ---------------- 6.8/11.9 MB 106.4 kB/s eta 0:00:48
     ---------------------- ---------------- 6.8/11.9 MB 106.4 kB/s eta 0:00:48
     ---------------------- ---------------- 6.8/11.9 MB 106.4 kB/s eta 0:00:48
     ---------------------- ---------------- 6.8/11.9 MB 106.4 kB/s eta 0:00:48
     ---------------------- ---------------- 6.8/11.9 MB 106.4 kB/s eta 0:00:48
     ---------------------- ---------------- 6.8/11.9 MB 106.4 kB/s eta 0:00:48
     ---------------------- ---------------- 6.8/11.9 MB 106.4 kB/s eta 0:00:48
     ---------------------- ---------------- 6.8/11.9 MB 106.4 kB/s eta 0:00:48
     ---------------------- ---------------- 6.8/11.9 MB 106.4 kB/s eta 0:00:48
     ---------------------- ---------------- 6.8/11.9 MB 106.4 kB/s eta 0:00:48
     ---------------------- ---------------- 6.8/11.9 MB 106.4 kB/s eta 0:00:48
     ----------------------- --------------- 7.1/11.9 MB 106.3 kB/s eta 0:00:45
     ----------------------- --------------- 7.1/11.9 MB 106.3 kB/s eta 0:00:45
     ----------------------- --------------- 7.1/11.9 MB 106.3 kB/s eta 0:00:45
     ----------------------- --------------- 7.1/11.9 MB 106.3 kB/s eta 0:00:45
     ----------------------- --------------- 7.1/11.9 MB 106.3 kB/s eta 0:00:45
     ----------------------- --------------- 7.1/11.9 MB 106.3 kB/s eta 0:00:45
     ----------------------- --------------- 7.1/11.9 MB 106.3 kB/s eta 0:00:45
     ----------------------- --------------- 7.1/11.9 MB 106.3 kB/s eta 0:00:45
     ----------------------- --------------- 7.1/11.9 MB 106.3 kB/s eta 0:00:45
     ----------------------- --------------- 7.1/11.9 MB 106.3 kB/s eta 0:00:45
     ------------------------ --------------- 7.3/11.9 MB 95.6 kB/s eta 0:00:48
     ------------------------ --------------- 7.3/11.9 MB 95.6 kB/s eta 0:00:48
     ------------------------ --------------- 7.3/11.9 MB 95.6 kB/s eta 0:00:48
     ------------------------ --------------- 7.3/11.9 MB 95.6 kB/s eta 0:00:48
     ------------------------ --------------- 7.3/11.9 MB 95.6 kB/s eta 0:00:48
     ------------------------ --------------- 7.3/11.9 MB 95.6 kB/s eta 0:00:48
     ------------------------ --------------- 7.3/11.9 MB 95.6 kB/s eta 0:00:48
     ------------------------ --------------- 7.3/11.9 MB 95.6 kB/s eta 0:00:48
     ------------------------ --------------- 7.3/11.9 MB 95.6 kB/s eta 0:00:48
     ------------------------ --------------- 7.3/11.9 MB 95.6 kB/s eta 0:00:48
     ------------------------ --------------- 7.3/11.9 MB 95.6 kB/s eta 0:00:48
     ------------------------- -------------- 7.6/11.9 MB 97.5 kB/s eta 0:00:44
     ------------------------- -------------- 7.6/11.9 MB 97.5 kB/s eta 0:00:44
     ------------------------- -------------- 7.6/11.9 MB 97.5 kB/s eta 0:00:44
     ------------------------- -------------- 7.6/11.9 MB 97.5 kB/s eta 0:00:44
     ------------------------- -------------- 7.6/11.9 MB 97.5 kB/s eta 0:00:44
     ------------------------- -------------- 7.6/11.9 MB 97.5 kB/s eta 0:00:44
     ------------------------- -------------- 7.6/11.9 MB 97.5 kB/s eta 0:00:44
     ------------------------- -------------- 7.6/11.9 MB 97.5 kB/s eta 0:00:44
     ------------------------- -------------- 7.6/11.9 MB 97.5 kB/s eta 0:00:44
     ------------------------- ------------- 7.9/11.9 MB 101.1 kB/s eta 0:00:40
     ------------------------- ------------- 7.9/11.9 MB 101.1 kB/s eta 0:00:40
     ------------------------- ------------- 7.9/11.9 MB 101.1 kB/s eta 0:00:40
     ------------------------- ------------- 7.9/11.9 MB 101.1 kB/s eta 0:00:40
     ------------------------- ------------- 7.9/11.9 MB 101.1 kB/s eta 0:00:40
     ------------------------- ------------- 7.9/11.9 MB 101.1 kB/s eta 0:00:40
     ------------------------- ------------- 7.9/11.9 MB 101.1 kB/s eta 0:00:40
     ------------------------- ------------- 7.9/11.9 MB 101.1 kB/s eta 0:00:40

In [9]:
import pandas as pd

In [10]:
import mysql.connector

In [13]:
conn=mysql.connector.connect(host='localhost',user='root',password='',database='world')

In [14]:
pd.read_sql_query("SELECT * FROM city",conn)

C:\Users\anjal\AppData\Local\Temp\ipykernel_19180\374620591.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM city",conn)

        ID            Name CountryCode       District  Population
0        1           Kabul         AFG          Kabol     1780000
1        2        Qandahar         AFG       Qandahar      237500
2        3           Herat         AFG          Herat      186800
3        4  Mazar-e-Sharif         AFG          Balkh      127800
4        5       Amsterdam         NLD  Noord-Holland      731200
...    ...             ...         ...            ...         ...
4074  4075      Khan Yunis         PSE     Khan Yunis      123175
4075  4076          Hebron         PSE         Hebron      119401
4076  4077        Jabaliya         PSE     North Gaza      113901
4077  4078          Nablus         PSE         Nablus      100231
4078  4079           Rafah         PSE          Rafah       92020

[4079 rows x 5 columns]

In [16]:
pd.read_sql_query("SELECT * FROM city WHERE CountryCode LIKE 'IND'",conn)

C:\Users\anjal\AppData\Local\Temp\ipykernel_19180\1285320557.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM city WHERE CountryCode LIKE 'IND'",conn)

       ID                Name CountryCode        District  Population
0    1024     Mumbai (Bombay)         IND     Maharashtra    10500000
1    1025               Delhi         IND           Delhi     7206704
2    1026  Calcutta [Kolkata]         IND    West Bengali     4399819
3    1027    Chennai (Madras)         IND      Tamil Nadu     3841396
4    1028           Hyderabad         IND  Andhra Pradesh     2964638
..    ...                 ...         ...             ...         ...
336  1360        Ambala Sadar         IND         Haryana       90712
337  1361          Baidyabati         IND    West Bengali       90601
338  1362               Morvi         IND         Gujarat       90357
339  1363             Raigarh         IND     Chhatisgarh       89166
340  1364            Vejalpur         IND         Gujarat       89053

[341 rows x 5 columns]

In [19]:
pd.read_sql_query("SELECT * FROM city WHERE CountryCode LifeExpectancy>60",conn)

C:\Users\anjal\AppData\Local\Temp\ipykernel_19180\651948733.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM city WHERE CountryCode LifeExpectancy>60",conn)

DatabaseError: Execution failed on sql 'SELECT * FROM city WHERE CountryCode LifeExpectancy>60': 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LifeExpectancy>60' at line 1